In [4]:
import numpy as np
A = np.array([[3,-1],[-1,3]])
print('打印A：\n{}'.format(A))
a, b = np.linalg.eig(A)
print('打印特征值a：\n{}'.format(a))
print('打印特征向量b：\n{}'.format(b))

打印A：
[[ 3 -1]
 [-1  3]]
打印特征值a：
[4. 2.]
打印特征向量b：
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [1]:
import numpy as np
A = np.array([[1, 5, 5 / 7, 5 / 3, 5 / 9], 
              [1 / 5, 1, 1 / 7, 1 / 3, 1 / 9],
              [7 / 5, 7, 1, 3 / 7, 1 / 3],
              [3 / 5, 3, 7 / 3, 1, 1 / 3],
              [9 / 5, 9, 3, 3, 1]
             ])
print(A)
a, b = np.linalg.eig(A)
print('打印特征值a：\n{}'.format(a))
print('打印特征向量b：\n{}'.format(b))


[[1.         5.         0.71428571 1.66666667 0.55555556]
 [0.2        1.         0.14285714 0.33333333 0.11111111]
 [1.4        7.         1.         0.42857143 0.33333333]
 [0.6        3.         2.33333333 1.         0.33333333]
 [1.8        9.         3.         3.         1.        ]]
打印特征值a：
[ 5.33522175e+00+0.j         -1.67610876e-01+1.32679651j
 -1.67610876e-01-1.32679651j -2.42810316e-17+0.j
 -1.14302338e-16+0.j        ]
打印特征向量b：
[[-3.76521266e-01+0.j          2.92125688e-01+0.2679641j
   2.92125688e-01-0.2679641j   6.43413268e-01+0.j
  -2.44778455e-01+0.j        ]
 [-7.53042532e-02+0.j          5.84251376e-02+0.05359282j
   5.84251376e-02-0.05359282j -1.04063529e-01+0.j
   1.74869430e-02+0.j        ]
 [-3.37903059e-01+0.j          1.81132624e-01-0.53315559j
   1.81132624e-01+0.53315559j  7.18350993e-17+0.j
  -1.48330385e-17+0.j        ]
 [-3.46549709e-01+0.j         -6.10438651e-01+0.j
  -6.10438651e-01-0.j          1.72333875e-01+0.j
  -2.20281236e-01+0.j        ]
 [-7.8631

In [30]:
import numpy as np;
A =np.array([[0.2500, 0, 0, 0],
             [0.7500, 0, 0, 0],
             
             [0, 0.2603, 0, 0],
             [0, 0.4420, 0, 0],
             [0, 0.1608, 0, 0],
             [0, 0.0876, 0, 0],
             [0, 0.0493, 0, 0],
             [0, 0, 0.1667, 0],
             [0, 0, 0.8333, 0],
          
             [0, 0, 0, 0.1277],
             [0, 0, 0, 0.0492],
             [0, 0, 0, 0.2233],
             [0, 0, 0, 0.0792],
             [0, 0, 0, 0.5207],
            ])

B = np.array([[0.0879, 0.6694, 0.6370, 0.6694, 0.6370, 0.6694, 0.1047, 0.6370, 0.1047, 0.1884, 0.1396, 0.6370, 0.6370, 0.1047],
              [0.6694, 0.0879, 0.1047, 0.2426, 0.1047, 0.0879, 0.6370, 0.2583, 0.2583, 0.7306, 0.5278, 0.2583, 0.2583, 0.6370],
              [0.2426, 0.2426, 0.2583, 0.0879, 0.2583, 0.2426, 0.2583, 0.1047, 0.6370, 0.0810, 0.3325, 0.1047, 0.1047, 0.2583]
             ])

C = np.array([[0.1861],
              [0.4954],
              [0.2465],
              [0.0720],
             ])
A_T = A.T
B_T = B.T
D = np.dot(A_T, B_T)
D_T = D.T
ans = np.dot(D_T, C)
# print('\nA矩阵如下:\n', A)
# print('\n--------\nB矩阵如下:\n', B)
# print('\n--------\nB的转置矩阵如下:\n', B_T)
# print('\n*******\nC矩阵如下\n', C)
print('\n\n决策的权重向量:\n', ans)



决策的权重向量:
 [[0.47629839]
 [0.23951301]
 [0.2841506 ]]
